### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yustme** [pocin/kbc-ex-instragram-scraper#1]
Hi,
we got an error while running this component:
```
failed: (2) Traceback (most recent call last):
  File "/code/main.py", line 81, in <module>
    main(os.environ['KBC_DATADIR'])
  File "/code/main.py", line 70, in main
    data = scraper.user_metadata_from_post(post['post_link'])
  File "/code/main.py", line 33, in user_metadata_from_post
    js_data = self._extract_js_data_from_resp(resp)
  File "/code/main.py", line 54, in _extract_js_data_from_resp
    if x.text.startswith('window._sharedData')][0]
IndexError: list index out of range
```

Can you please check it ? Thanks.

**Comment by pocin** [comment]
Hi, sorry for the delay here. This error happens to us from time to time,  but usually it goes away on next run so we didn't worry about this too much.
Since the component is just a dumb scraper under the hood, there is no easy way of figuring out what went wrong. It doesn't bother our use case too much so we didn't want to invest too much time to perfect this component.
I will happily accept a PR if you figure this out.

btw how did you find about this component? I thought it was private

**Comment by yustme** [comment]
Hi @pocin I'm a developer at Keboola and I've found this inside our logs (that the way how I've discovered it).

If error doesn't bother you, feel free to close the issue.

**Comment by pocin** [comment]
oh right! If the internal errors make mess in your logs, I can catch those errors as user errors not system errors

**Comment by pocin** [comment]
Acutally I'll fix it. Thanks for the notification 🍺
